In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [11]:
# 文本文档列表
text=["the quick brown fox jumped over the lazy dog.","the dog.","the fox"]

In [12]:
# 创建实例
vectorizer=TfidfVectorizer()


In [13]:
# 词条化以及创建词汇表
vectorizer.fit(text)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [14]:
# 查看vectorizer参数
vectorizer.vocabulary_# 查看建立的词汇表

{'brown': 0,
 'dog': 1,
 'fox': 2,
 'jumped': 3,
 'lazy': 4,
 'over': 5,
 'quick': 6,
 'the': 7}

In [15]:
vectorizer.idf_# 词汇出现频率高的idf反而低

array([1.69314718, 1.28768207, 1.28768207, 1.69314718, 1.69314718,
       1.69314718, 1.69314718, 1.        ])

In [23]:
# 编码文档
vector=vectorizer.transform([text[0]])

In [24]:
#查看编码后的文档
vector.shape

(1, 8)

In [25]:
vector.toarray()#对比第一个文档的内容看一下：
#the quick brown fox jumped over the lazy dog
#词汇表 brown': 0,'dog': 1,'fox': 2,'jumped': 3,'lazy': 4,'over': 5,'quick': 6,'the': 7}
#。     1,          1,       1,         1,         1,        1,        1,        2

array([[0.36388646, 0.27674503, 0.27674503, 0.36388646, 0.36388646,
        0.36388646, 0.36388646, 0.42983441]])

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

In [27]:
vec=CountVectorizer()
vec.fit(text)
v=vec.transform([text[0]])
v.toarray()# 

array([[1, 1, 1, 1, 1, 1, 1, 2]])

{'brown': 0,
 'dog': 1,
 'fox': 2,
 'jumped': 3,
 'lazy': 4,
 'over': 5,
 'quick': 6,
 'the': 7}